name: 'Koha Branch by Label'
description: 'Returns the current branch name for a given Koha version label'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  version-label:  # id of input
    description: 'The label of the branch you are looking for ( i.e. main, stable, oldstable )'
    required: true
outputs:
  current-branch-name: # id of output
    description: 'The name of the branch that currently matches the given version label ( e.g. main, 19.11.x, 19.05.x, etc... )'
  branch-name:
    description: 'same as current-branch-name'
  version-major-minor:
    description: 'Major and minor version number for this version of Koha'
  version-major:
    description: 'Major version number for this version of Koha'
  version-minor:
    description: 'Minor version number for this version of Koha'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version-label }}
