name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-label: [main, stable, oldstable]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Koha Version Action
      id: koha-version
      uses: ./
      with:
        version-label: ${{ matrix.version-label }}
    
    - name: Verify outputs
      run: |
        echo "Testing version-label: ${{ matrix.version-label }}"
        echo "current-branch-name: ${{ steps.koha-version.outputs.current-branch-name }}"
        echo "branch-name: ${{ steps.koha-version.outputs.branch-name }}"
        echo "version-major-minor: ${{ steps.koha-version.outputs.version-major-minor }}"
        echo "version-major: ${{ steps.koha-version.outputs.version-major }}"
        echo "version-minor: ${{ steps.koha-version.outputs.version-minor }}"
        
        # Verify current-branch-name is not empty
        if [[ -z "${{ steps.koha-version.outputs.current-branch-name }}" ]]; then
          echo "ERROR: current-branch-name is empty"
          exit 1
        fi
        
        # Verify branch name format
        BRANCH_NAME="${{ steps.koha-version.outputs.current-branch-name }}"
        if [[ "${{ matrix.version-label }}" == "main" ]]; then
          # For main, expect exactly "main"
          if [[ "$BRANCH_NAME" != "main" ]]; then
            echo "ERROR: Expected 'main' for main label, got '$BRANCH_NAME'"
            exit 1
          fi
          echo "✅ Main branch name correct: $BRANCH_NAME"
        else
          # For stable/oldstable, expect format like "25.05.x" or "24.11.x"
          if [[ ! "$BRANCH_NAME" =~ ^[0-9]{2}\.[0-9]{2}\.x$ ]]; then
            echo "ERROR: Expected format 'XX.YY.x' for ${{ matrix.version-label }}, got '$BRANCH_NAME'"
            exit 1
          fi
          
          # Verify version outputs are populated for versioned branches
          if [[ -z "${{ steps.koha-version.outputs.version-major-minor }}" ]]; then
            echo "ERROR: version-major-minor is empty for ${{ matrix.version-label }}"
            exit 1
          fi
          
          if [[ -z "${{ steps.koha-version.outputs.version-major }}" ]]; then
            echo "ERROR: version-major is empty for ${{ matrix.version-label }}"
            exit 1
          fi
          
          if [[ -z "${{ steps.koha-version.outputs.version-minor }}" ]]; then
            echo "ERROR: version-minor is empty for ${{ matrix.version-label }}"
            exit 1
          fi
          
          echo "✅ Version branch name correct: $BRANCH_NAME"
          echo "✅ Version parts: ${{ steps.koha-version.outputs.version-major }}.${{ steps.koha-version.outputs.version-minor }}"
        fi
        
        echo "✅ All outputs verified successfully for ${{ matrix.version-label }}"
